use super::register::Flags;

#[derive(Debug)]
pub(crate) enum Instruction {
    ADC(AddressMode),
    AND(AddressMode),
    ASL(AddressMode),
    BIT(AddressMode),
    BCC,
    BCS,
    BEQ,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLR(Flags),
    CMP(AddressMode),
    CPX(AddressMode),
    CPY(AddressMode),
    DEC(AddressMode),
    DEX,
    DEY,
    EOR(AddressMode),
    INC(AddressMode),
    INX,
    INY,
    JMP(AddressMode),
    JSR,
    LDA(AddressMode),
    LDX(AddressMode),
    LDY(AddressMode),
    LSR(AddressMode),
    NOP,
    ORA(AddressMode),
    PHA,
    PHP,
    PLA,
    PLP,
    ROL(AddressMode),
    ROR(AddressMode),
    RTI,
    RTS,
    SBC(AddressMode),
    SET(Flags),
    STA(AddressMode),
    STX(AddressMode),
    STY(AddressMode),
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
}

#[derive(Copy,Clone,Debug)]
pub(crate) enum AddressMode {
    Accumulator,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Immediate,
    Indirect,
    XIndirect,
    IndirectY,
    Relative,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
}

pub(crate) fn decode(opcode: u8) -> Instruction {
    match opcode {
        0x00 => Instruction::BRK,
        0x01 => Instruction::ORA(AddressMode::XIndirect),
        0x05 => Instruction::ORA(AddressMode::ZeroPage),
        0x06 => Instruction::ASL(AddressMode::ZeroPage),
        0x08 => Instruction::PHP,
        0x09 => Instruction::ORA(AddressMode::Immediate),
        0x0A => Instruction::ASL(AddressMode::Accumulator),
        0x0D => Instruction::ORA(AddressMode::Absolute),
        0x0E => Instruction::ASL(AddressMode::Accumulator),
        0x10 => Instruction::BPL,
        0x11 => Instruction::ORA(AddressMode::IndirectY),
        0x15 => Instruction::ORA(AddressMode::ZeroPageX),
        0x16 => Instruction::ASL(AddressMode::ZeroPageX),
        0x18 => Instruction::CLR(Flags::C),
        0x19 => Instruction::ORA(AddressMode::AbsoluteY),
        0x1D => Instruction::ORA(AddressMode::AbsoluteX),
        0x1E => Instruction::ASL(AddressMode::AbsoluteX),
        0x20 => Instruction::JSR,
        0x21 => Instruction::AND(AddressMode::XIndirect),
        0x24 => Instruction::BIT(AddressMode::ZeroPage),
        0x25 => Instruction::AND(AddressMode::ZeroPage),
        0x26 => Instruction::ROL(AddressMode::ZeroPage),
        0x28 => Instruction::PLP,
        0x29 => Instruction::AND(AddressMode::Immediate),
        0x2A => Instruction::ROL(AddressMode::Accumulator),
        0x2C => Instruction::BIT(AddressMode::Absolute),
        0x2D => Instruction::AND(AddressMode::Absolute),
        0x2E => Instruction::ROL(AddressMode::Absolute),
        0x30 => Instruction::BMI,
        0x31 => Instruction::AND(AddressMode::IndirectY),
        0x35 => Instruction::AND(AddressMode::ZeroPageX),
        0x36 => Instruction::ROL(AddressMode::ZeroPageX),
        0x38 => Instruction::SET(Flags::C),
        0x39 => Instruction::AND(AddressMode::AbsoluteY),
        0x3D => Instruction::AND(AddressMode::AbsoluteX),
        0x3E => Instruction::ROL(AddressMode::AbsoluteX),
        0x40 => Instruction::RTI,
        0x41 => Instruction::EOR(AddressMode::XIndirect),
        0x45 => Instruction::EOR(AddressMode::ZeroPage),
        0x46 => Instruction::LSR(AddressMode::ZeroPage),
        0x48 => Instruction::PHA,
        0x49 => Instruction::EOR(AddressMode::Immediate),
        0x4A => Instruction::LSR(AddressMode::Accumulator),
        0x4C => Instruction::JMP(AddressMode::Absolute),
        0x4D => Instruction::EOR(AddressMode::Absolute),
        0x4E => Instruction::LSR(AddressMode::Absolute),
        0x50 => Instruction::BVC,
        0x51 => Instruction::EOR(AddressMode::IndirectY),
        0x55 => Instruction::EOR(AddressMode::ZeroPageX),
        0x56 => Instruction::LSR(AddressMode::ZeroPageX),
        0x58 => Instruction::CLR(Flags::I),
        0x59 => Instruction::EOR(AddressMode::AbsoluteY),
        0x5D => Instruction::EOR(AddressMode::AbsoluteX),
        0x5E => Instruction::LSR(AddressMode::AbsoluteX),
        0x60 => Instruction::RTS,
        0x61 => Instruction::ADC(AddressMode::XIndirect),
        0x65 => Instruction::ADC(AddressMode::ZeroPage),
        0x66 => Instruction::ROR(AddressMode::ZeroPage),
        0x68 => Instruction::PLA,
        0x69 => Instruction::ADC(AddressMode::Immediate),
        0x6A => Instruction::ROR(AddressMode::Accumulator),
        0x6C => Instruction::JMP(AddressMode::Indirect),
        0x6D => Instruction::ADC(AddressMode::Absolute),
        0x6E => Instruction::ROR(AddressMode::Absolute),
        0x70 => Instruction::BVS,
        0x71 => Instruction::ADC(AddressMode::IndirectY),
        0x75 => Instruction::ADC(AddressMode::ZeroPageX),
        0x76 => Instruction::ROR(AddressMode::ZeroPageX),
        0x78 => Instruction::SET(Flags::I),
        0x79 => Instruction::ADC(AddressMode::AbsoluteY),
        0x7D => Instruction::ADC(AddressMode::AbsoluteX),
        0x7E => Instruction::ROR(AddressMode::AbsoluteX),
        0x81 => Instruction::STA(AddressMode::XIndirect),
        0x84 => Instruction::STY(AddressMode::ZeroPage),
        0x85 => Instruction::STA(AddressMode::ZeroPage),
        0x86 => Instruction::STX(AddressMode::ZeroPage),
        0x88 => Instruction::DEY,
        0x8A => Instruction::TXA,
        0x8C => Instruction::STY(AddressMode::Absolute),
        0x8D => Instruction::STA(AddressMode::Absolute),
        0x8E => Instruction::STX(AddressMode::Absolute),
        0x90 => Instruction::BCC,
        0x91 => Instruction::STA(AddressMode::IndirectY),
        0x94 => Instruction::STY(AddressMode::ZeroPageX),
        0x95 => Instruction::STA(AddressMode::ZeroPageX),
        0x96 => Instruction::STX(AddressMode::ZeroPageY),
        0x98 => Instruction::TYA,
        0x99 => Instruction::STA(AddressMode::AbsoluteY),
        0x9A => Instruction::TXS,
        0x9D => Instruction::STA(AddressMode::AbsoluteX),
        0xA0 => Instruction::LDY(AddressMode::Immediate),
        0xA1 => Instruction::LDA(AddressMode::XIndirect),
        0xA2 => Instruction::LDX(AddressMode::Immediate),
        0xA4 => Instruction::LDY(AddressMode::ZeroPage),
        0xA5 => Instruction::LDA(AddressMode::ZeroPage),
        0xA6 => Instruction::LDX(AddressMode::ZeroPage),
        0xA8 => Instruction::TAY,
        0xA9 => Instruction::LDA(AddressMode::Immediate),
        0xAA => Instruction::TAX,
        0xAC => Instruction::LDY(AddressMode::Absolute),
        0xAD => Instruction::LDA(AddressMode::Absolute),
        0xAE => Instruction::LDX(AddressMode::Absolute),
        0xB0 => Instruction::BCS,
        0xB1 => Instruction::LDA(AddressMode::IndirectY),
        0xB4 => Instruction::LDY(AddressMode::ZeroPageX),
        0xB5 => Instruction::LDA(AddressMode::ZeroPageX),
        0xB6 => Instruction::LDX(AddressMode::ZeroPageY),
        0xB8 => Instruction::CLR(Flags::V),
        0xB9 => Instruction::LDA(AddressMode::AbsoluteY),
        0xBA => Instruction::TSX,
        0xBC => Instruction::LDY(AddressMode::AbsoluteX),
        0xBD => Instruction::LDA(AddressMode::AbsoluteX),
        0xBE => Instruction::LDX(AddressMode::AbsoluteY),
        0xC0 => Instruction::CPY(AddressMode::Immediate),
        0xC1 => Instruction::CMP(AddressMode::XIndirect),
        0xC4 => Instruction::CPY(AddressMode::ZeroPage),
        0xC5 => Instruction::CMP(AddressMode::ZeroPage),
        0xC6 => Instruction::DEC(AddressMode::ZeroPage),
        0xC8 => Instruction::INY,
        0xC9 => Instruction::CMP(AddressMode::Immediate),
        0xCA => Instruction::DEX,
        0xCC => Instruction::CPY(AddressMode::Absolute),
        0xCD => Instruction::CMP(AddressMode::Absolute),
        0xCE => Instruction::DEC(AddressMode::Absolute),
        0xD0 => Instruction::BNE,
        0xD1 => Instruction::CMP(AddressMode::IndirectY),
        0xD5 => Instruction::CMP(AddressMode::ZeroPageX),
        0xD6 => Instruction::DEC(AddressMode::ZeroPageX),
        0xD8 => Instruction::CLR(Flags::D),
        0xD9 => Instruction::CMP(AddressMode::AbsoluteY),
        0xDD => Instruction::CMP(AddressMode::AbsoluteX),
        0xDE => Instruction::DEC(AddressMode::AbsoluteX),
        0xE0 => Instruction::CPX(AddressMode::Immediate),
        0xE1 => Instruction::SBC(AddressMode::XIndirect),
        0xE4 => Instruction::CPX(AddressMode::ZeroPage),
        0xE5 => Instruction::SBC(AddressMode::ZeroPage),
        0xE6 => Instruction::INC(AddressMode::ZeroPage),
        0xE8 => Instruction::INX,
        0xE9 => Instruction::SBC(AddressMode::Immediate),
        0xEA => Instruction::NOP,
        0xEC => Instruction::CPX(AddressMode::Absolute),
        0xED => Instruction::SBC(AddressMode::Absolute),
        0xEE => Instruction::INC(AddressMode::Absolute),
        0xF0 => Instruction::BEQ,
        0xF1 => Instruction::SBC(AddressMode::IndirectY),
        0xF5 => Instruction::SBC(AddressMode::ZeroPageX),
        0xF6 => Instruction::INC(AddressMode::ZeroPageX),
        0xF8 => Instruction::SET(Flags::D),
        0xF9 => Instruction::SBC(AddressMode::AbsoluteX),
        0xFD => Instruction::SBC(AddressMode::AbsoluteX),
        0xFE => Instruction::INC(AddressMode::AbsoluteX),
        _ => panic!("Unsupported instruction"),
    }
}


